#!/usr/bin/env python3
#
# ingest the TXT file generated by "mtr" and read it as records

import sys
if sys.version < "3.4":
    raise RuntimeError("validator requires Pyton 3.4 or above")
import os,datetime,re



HOSTIP = re.compile("(.*) \\((\d+[.]\d+[.]\d+[.]\d+)\\)")
class MtrRecord():
    __slots__ = ['timet','destination','hop','hostname','ipaddr','usec']
    def __init__(self,line):
        # Parse line and fill these in.
        # ts is the timestamp that we previously found
        parts = line.strip().split(";")
        if parts[0]=='MTR.0.85':
            self.timet = int(parts[1])
            self.destination = parts[3]
            self.hop = int(parts[4])
            m = HOSTIP.search(parts[5])
            if m:
                self.hostname = m.group(1)
                self.ipaddr = m.group(2)
            else:
                self.ipaddr = parts[5]
                self.hostname = None
        self.usec = int(parts[6])
    def __str__(self):
        return f"{self.timet}:{self.destination}:{self.hop}:{self.hostname}:{self.ipaddr}:{self.usec}"
        
    
